service: webcrawler
frameworkVersion: '3'

# 自定義自己的變數
custom:
  bookstore: bookstore

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource:
            - Fn::GetAtt: ['${self:custom.bookstore}', Arn]
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:BatchWriteItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem

  environment:
    TABLE_NAME:
      Ref: ${self:custom.bookstore}

# 自定義需額外佈署的AWS資源，設定DB
resources:
  Resources:
    bookstore:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookstore
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
# 當lambda function 啟動時的進入點，要用哪些layer

functions:
  scrape:
    handler: api/handler.scrape
    events:
      - http:
          path: scrape
          method: get
  getBooks:
    handler: api/handler.list
    events:
      - http:
          path: list
          method: get
  writeBook:
    handler: api/handler.testWrite
    events:
      - http:
          path: testWrite
          method: get
