service: webcrawler
frameworkVersion: '3'

# 自定義自己的變數
custom:
  bookstore: bookstore

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x

environment:
  TABLE_NAME:
    Ref: self:custom.bookstore

# 當lambda function 啟動時的進入點，要用哪些layer
functions:
  scrape:
    handler: api/handler.scrape
    iamRoleStatementsName: admin
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: 'arn:aws:dynamodb:us-east-1:655258975055:table/bookstore'
    events:
      - http:
          path: scrape
          method: get
          #cors: true

# 自定義需額外佈署的AWS資源
resources:
  Resources:
    myTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.bookstore}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
